export const handleException = (message) => {
	console.log(`Error: ${message}`)
}
